### ISSUE TITLE
error TS2665: Invalid module name in augmentation

### ISSUE THREAD

**Issue by dsebastien** [apollographql/apollo-cache-control#4]
I stumbled upon this issue while trying the hello world tutorial for Apollo with TypeScript: `node_modules/apollo-cache-control/lib/index.d.ts(20,16): error TS2665: Invalid module name in augmentation. Module 'graphql/type/definition' resolves to an untyped module at 'C:/dev/wks/bedeals-mvp/functions/node_modules/graphql/type/definition.js', which cannot be augmented.`.

Did you already see this before?

I'm apparently using apollo-cache-control 0.1.0 through apollo-server-express. I also have graphql-tools 2.23.1.

**Comment by cbacken** [comment]
Exact same issue here as well.

Typescript Version 2.8.1.
apollo-server-express: 1.3.4
graphql-tools: 2.23.1

**Comment by dsebastien** [comment]
I think this issue can be closed for my case; as I've explained in https://github.com/apollographql/apollo-server/issues/927, my problem was caused by incorrect imports for apollo-server-express.

**Comment by tsukhu** [comment]
I did try what @dsebastien mentioned but still got the same compilation error .. So reverted back to the version which was working for the nxplorerjs project (https://github.com/ERS-HCL/nxplorerjs-microservice-starter/pull/112)  . I guess it is a combination of multiple libraries including graphql which is causing it.

**Comment by whatupdave** [comment]
I fixed it by installing the types for graphql
```
npm i --save-dev @types/graphql
```

**Comment by rgoyardgop** [comment]
Hi, 

We currently experience the same issue :

```
/../node_modules/apollo-cache-control/dist/index.d.ts:22:16 - error TS2665: Invalid module name in augmentation. Module 'graphql/type/definition' resolves to an untyped module at '.../node_modules/graphql/type/definition.js', which cannot be augmented.

22 declare module 'graphql/type/definition' {
```

Typescript Version 3.2.1
apollo-server-express: 2.2.6
graphql: 14.0.2
graphql-tools: N/A
@types/graphql: 14.0.3

here is our tsconfig.json : 

```
{
    "compilerOptions": {
        "outDir": "./build/",
        "module": "commonjs",
        "target": "es6",
        "experimentalDecorators": true,
        "sourceMap": true,
        "allowSyntheticDefaultImports": true,
        "declaration": false,
        "emitDecoratorMetadata": true,
        "moduleResolution": "node",
        "removeComments": false,
        "strict": false,
        "baseUrl": ".",
        "lib": [
            "dom",
            "es2017",
            "esnext.asynciterable"
        ],
        "typeRoots": ["node_modules/@types"]
    },
    "include": [
        "./src/**/*.ts"
    ],
    "exclude": [
        "./node_modules",
        "./data/",
        "./src/**/test/*.test.ts",
        "./test/"
    ]
}
```

If have any ideas would appreciate ...

Regards

Rémi

**Comment by brianschardt** [comment]
Experiencing the same issue as above

**Comment by martijnwalraven** [comment]
@rgoyardgop @brianalois Can you check if there's a stray version of `@types/graphql` lingering anywhere in your `node_modules`? It seems TypeScript isn't picking up the right one.

**Comment by rgoyardgop** [comment]
Hi for me the problem was due to misconfiguration of my lerna / yarn workspaces  repository. And because typescript, if there is some `@types/*` forlders in the forlder tree (parents included), will try to compile them even if they are not used in the project. Sorry for the bad reporting 

@martijnwalraven thanks for your time.
